name: hello_food
description: A simple food ordering Flutter app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  razorpay_flutter: ^1.3.6
  url_launcher: ^6.3.0
  http: ^1.2.1       # âœ… Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/vegi.jpg
    - assets/images/friedegg.jpeg
    - assets/images/Poha-Recipe.jpg
    - assets/images/noddles.jpg
    - assets/images/maggie.webp
    - assets/images/gobirice.jpeg
    - assets/images/Masala_Dosa.jpg
    - assets/images/paneer_paratha.jpg
    - assets/images/idli_sambar.jpg
